### ISSUE TITLE
Overclock

### ISSUE THREAD

**Issue by archeart23** [asakous/Neo-EmuELEC-H3#11]
Did you set the clock speeds for this? And if not is it possible to clock it up a notch?

Just a little bit more juice to play dolphin blue better would be nice haha

Btw Im testing ROMs and I've seen a slow loading speed with my nes that are converter to .rar

**Comment by asakous** [comment]
I did overclock to 1.6G . but it doesn't helped too much. because the weak GPU.
and there are too many H3 variant some can overclock and some don't.
if you want to overclock. do it by yourself . there are tons of information on the internet. 

rar may save disk space but slow decompress. 
in general I would like to use zip for speed.
