### ISSUE TITLE
Orange Pi lite H3

### ISSUE THREAD

**Issue by KaleoStore** [asakous/Neo-EmuELEC-H3#28]
How do I adapt to the system to work on my Orange Pi Lite H3? The hardware is practically the same, which file to configure to run the system on this card?

**Comment by asakous** [comment]
currently . there is no Orange Pi lite image for this project. please wait for next release.

**Comment by asakous** [comment]
released

**Comment by KaleoStore** [comment]
> released

I'm already testing here, it looks great. Excellent performance gains on some Nintendo 64 games. Congratulations!

**Comment by KaleoStore** [comment]
During the tests I noticed the following problems: Background music does not work, FBA games (capcom) and Neo Geo are slow, PSX games only generate a red screen. Would it be possible to release a version for Orange Pi lite using Emuelec 3.9? Version 4.0 of Emuelec has many bugs.

**Comment by asakous** [comment]
no  Emuelec 3.9 any more. and 512mb of ram is not recommend for EmuELEC. 

I tested every problem you mentioned . none of them  happened on my orange pi pc.
since you did not provide good enough information for me to judge the problems. so I only can guess.
for Background music porblem . you may change  ee_audio_device=0,0 to 0,1 or 1,0 or 1,1 in /storage/.config/emuelec/configs/emuelec.conf , each time you changed the system need to be rebooted . 
I only test mp3 music . ogg not tested . 

since EmuELEC needs 1GB ram as least  so I suspect the problems is cause by low system memory. 
You may try change Retroarch setting . Settings Tab --> Directory --> Cache Dir  from /tmp to /storage/roms/mt32/ 
but this setting not only slow down game loading time but also increase damage to sd card.  good lock.

**Comment by KaleoStore** [comment]
I used Neo Emuelec v1.3 from Orange One on Orange Lite and it ran the games perfectly without bugs, the only problem is that it doesn't recognize Wi-Fi. If you manage to activate the Wi-Fi card of this version for the lite it will be perfect.

**Comment by asakous** [comment]
since I don't have Orange Pi Lite  . the wifi problem won't be fixed. 
and EmuELEC has update many cores and ES . the memory consumption may not be the same. 
but you can try copy v1.3 core to /storage/cores/ . after reboot the retroarch will use old core instead new one.
