### ISSUE TITLE
Component video support

### ISSUE THREAD

**Issue by franklinweise** [asakous/Neo-EmuELEC-H3#51]
I have an Orange Pi PC running Neo-Emuelec - everything runs fine, but there are no video out options for composite video (480/576 cvbs). Seems the support for this was dropped some time ago. Is there a way to make it work?

(BTW, I created the EE_VIDEO_MODE file with the resolution inside, but seems this isn't working for the latest releases).

**Comment by asakous** [comment]
there is no menu option to change hdmi output to composite output . since amlogic chip boot method is totally different from allwinner H3 chip. so the only way to achieve your request is to edit script.bin file. please check https://linux-sunxi.org/Fex_Guide#.5Bdisp_init.5D [disp init configuration part]
