### ISSUE TITLE
is it possible to add Gpio to your neo emuelec system?

### ISSUE THREAD

**Issue by ctogamez** [asakous/Neo-EmuELEC-H3#6]
Hello, asakous, all good.

My name is Fabio, and as a player, I use the nickname cto gamez. I am Brazilian and I love oldgen games.

I met this week, your neo emuelec project, and I was very surprised by this system, because it is doing something that I have not seen in other systems, running naomi system very fluidly in many games.
But with USB controls there is always a delay when playing. And I would like to know if it is possible to implement GPIO in your system, as I guarantee that it would be very good.

I thank you for the effort you have made in the scene with orange pi.
and my congratulations, and continue on this beautiful project

Ass: Cto Gamez

**Comment by Diego-Westcade** [comment]
It would be a great alternative and option to be able to play through Gpio ......

**Comment by asakous** [comment]
I am using  Xbox 360 with wireless dongle. there is no delay at all 
I also have a arcade USB Encoder  and it work very good too . 
and I also modified USB polling time ,theoretically input delay must be less than other systems.


let's be honest GPIO is less important to me. because I never used it.
I know there is a GPIO program for H3s , such as https://github.com/retr0rangepi/RetrOrangePi/tree/mainline/GPIO

someday I might add for you .

**Comment by ctogamez** [comment]
thank you very much for returning. And I and the community would be very grateful, on the day that you can add this option to your system.

**Comment by RichardCWB** [comment]
Good afternoon, Your system the neo emulec is very good, there is the possibility to add the GPIO on it for h3 to use on the orange pi pc so that you can choose your own system if we want to use the gpio or usb as is done in the recalbox .. I believe that this must be laborious that it should take a long time, if it were possible to do that I would not mind paying a fee for you so that it is possible to leave this function available in your system ... thank you for your attention !!

**Comment by Diego-Westcade** [comment]
Good morning Osakous, I spoke with some friends from the retrogamer community and we are willing to help financially your Neo Emuelec project so that you include the option of playing with gpio cables connected directly to the arcade levers and buttons.

We would be very grateful if you can activate gpio in the Neo Emuelec system.

Thanks for everything !!

**Comment by lamerjack** [comment]
Gpio joypad will be nice for the gameboy zero that i'm building!

**Comment by asakous** [comment]
please test new release v1.3. I added a GPIO service.

**Comment by ctogamez** [comment]
@asakous Thank you very much for this great update. I was very happy with this news. Now the system is perfect: D

**Comment by Diego-Westcade** [comment]
Thank you very much Mattew! hug

**Comment by edgarhouse08** [comment]
@asakous  ficou excelente essa ativação do gpio muito obrigado pela ajuda sera bem util.

**Comment by RichardCWB** [comment]
Muito obrigado por essa atualização ficou incrível!!!!!

**Comment by KaleoStore** [comment]
This system was amazing and GPIO works perfectly, however I found a BUG in GPIO. When a GPIO is activated and there is no USB control connected, when turning on the system a message appears saying that it does not have any controls connected, so that pressing a button on the GPIO to enter the system. Would there be any way to change it so that the system understands that GPIO is enabled and in that case there are connected controls eliminating this error message?

**Comment by asakous** [comment]
after searching on google . I find a link may help you. https://github.com/adafruit/Adafruit-Retrogame

**Comment by asakous** [comment]
@KaleoStore  since I use https://github.com/retr0rangepi/GPIO_controller-for-retrorangepi gpio script .  
according to readme . it should be  recognized by emulationstation .

**Comment by asakous** [comment]
no response . close for now.
